<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">New Menu</h1>
		<a href="<?php echo $this->url('menu-list')?>"><button class="btn btn-success pull-right" style="margin-top: -63px;">Menu List</button></a>
		<?php 
			if(!empty($this->errors)) {
				echo '<div class="alert alert-danger">';
				foreach($this->errors as $class => $msgArr) {
					foreach($msgArr as $message) {
						echo $message.'<br>';
					}
				}
				echo '</div>';
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">			
		<div class="panel panel-default">
			<div class="panel-heading">New Menu Section</div>
			<div class="panel-body">
				<?php
					$form = $this->menuForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-12">
					<div class="form-group">
						<label class="col-lg-2">Manu Name <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('name')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Parent Menu</label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('parent_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Description</label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('description')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Navigation</label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('is_navigation')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Active</label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('active')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Icon Url</label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('iconurl')); ?>
							<?php if($this->iconurl): ?>
							<div class="clear"></div>
							<img class="iconurl-logo" src="<?php echo $this->basePath(); ?>/uploads/menus/<?php echo $this->iconurl; ?>" >
							<?php endif; ?>
						</div>
					</div>					
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">&nbsp;</label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('save-menu')); ?>
							<?php echo $this->formElement($form->get('back')); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	
<!-- /.row -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('#country_id').change(function() {
			countryId = $(this).val();
			getStates(countryId,'');
		});
		countryId = $('#country_id').val();
		if(countryId) {
			getStates(countryId,"<?php echo $this->stateid; ?>");
		}
	});	
</script>