<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Installment
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('investors-list')?>" class="btn btn-primary">Go Back</a>
			</span>
		</h3>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Member Installment
		</div>
		<div class="panel-body">
			<div class="row">
				<?php
					$form = $this->installmentForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
					<?php if (count($this->errors)) : ?>
						<div class="alert alert-danger">
							<?php foreach ($this->errors as $error) : ?>
							<?php if(is_array($error)) : echo current($error); else: echo $error;endif;?><br>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
					<div class="col-lg-6">		
						<div class="form-group">
							<label>CF Number<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('cf_number')); ?>
							<?php echo $this->formElement($form->get('investment_id'));?>
						</div>
						<div class="form-group">
							<label>Period</label>
							<?php echo $this->formElement($form->get('period'));?>
						</div>	
						<div class="form-group">
							<label>Interest Rate</label>
							<?php echo $this->formElement($form->get('interest_rate'));?>
						</div>																										
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="col-lg-6">	
						<div class="form-group">
							<label>Amount</label>
							<?php echo $this->formElement($form->get('amount'));?>
						</div>	
						<div class="form-group">
							<label>Installment No</label>
							<?php echo $this->formElement($form->get('installment_no'));?>
						</div>	
						<div class="form-group">
							<label>Remaining Installment</label>
							<?php echo $this->formElement($form->get('total_installment'));?>
						</div>	
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="clear"></div>
					<div class="col-lg-12">
						<div class="pull-right">
							<a href="<?php echo $this->url("investors-list")?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
							<?php echo $this->formElement($form->get('save')); ?>								
						</div>							
					</div>
				</form>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
					
</div>
<script type="text/javascript">
	$(document).ready(function() {
		clearForm();
		$('#cf_number').keyup(function(){
			cf_number = $(this).val();
			if(cf_number) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/investment-details')?>',
					type:'post',
					data:{cf_number:cf_number},
					success:function(returns) {
						if(returns.status) {
							$('#investment_id').val(returns.response.data.investment_id);
							$('#installment_no').val(returns.response.data.installment_no);
							$('#total_installment').val(returns.response.data.total_installment);
							$('#interest_rate').val(returns.response.data.interest_rate);
							$('#period').val(returns.response.data.period);
							$('#amount').val(returns.response.data.ammount);
						} else {
							clearForm();
						}
					}
				});
			} else{
				clearForm();
			}
		});
		
		function clearForm(){
			$('#investment_id').val('');
			$('#installment_no').val('');
			$('#total_installment').val('');
			$('#interest_rate').val('');
			$('#period').val('');
			$('#amount').val('');
		}
	})
</script>