<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Installment</h3>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<?php echo $this->render('partials/flash-messages')?>
	<div class="panel panel-default">
		<div class="panel-heading">
			Member Installment
		</div>
		<div class="panel-body">
			<div class="row">
				<?php
					$form = $this->installmentForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
					<div class="col-lg-6">		
						<div class="form-group">
							<label>CF Number<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('cf_number')); ?>
							<?php if($this->formElementErrors($form->get('cf_number'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('cf_number')))?></div>
							<?php endif;?>
							<?php echo $this->formElement($form->get('investment_id'));?>
						</div>
						<div class="form-group">
							<label>Period</label>
							<?php echo $this->formElement($form->get('period'));?>
							<?php if($this->formElementErrors($form->get('period'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('period')))?></div>
							<?php endif;?>
						</div>	
						<div class="form-group">
							<label>Interest Rate</label>
							<?php echo $this->formElement($form->get('interest_rate'));?>
							<?php if($this->formElementErrors($form->get('interest_rate'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('interest_rate')))?></div>
							<?php endif;?>
						</div>																										
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="col-lg-6">	
						<div class="form-group">
							<label>Amount</label>
							<?php echo $this->formElement($form->get('amount'));?>
							<?php if($this->formElementErrors($form->get('amount'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('amount')))?></div>
							<?php endif;?>
						</div>	
						<div class="form-group">
							<label>Installment No</label>
							<?php echo $this->formElement($form->get('installment_no'));?>
							<?php if($this->formElementErrors($form->get('installment_no'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('installment_no')))?></div>
							<?php endif;?>
						</div>	
						<div class="form-group">
							<label>Remaining Installment</label>
							<?php echo $this->formElement($form->get('total_installment'));?>
							<?php if($this->formElementErrors($form->get('total_installment'))) :?>
							<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('total_installment')))?></div>
							<?php endif;?>
						</div>	
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="clear"></div>
					<div class="col-lg-12">
						<div class="pull-right">
							<a href="<?php echo $this->url("investors")?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
							<?php echo $this->formElement($form->get('save')); ?>								
						</div>							
					</div>
				</form>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
					
</div>
<script type="text/javascript">
	$(document).ready(function() {
		//clearForm();
		$('#cf_number').keyup(function(){
			cf_number = $(this).val();
			cfdetails(cf_number);
		});
		//cfdetails($('#cf_number').val());
		
		function cfdetails(cf_number) {
			if(cf_number) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/investment-details')?>',
					type:'post',
					data:{cf_number:cf_number},
					success:function(returns) {
						if(returns.status) {
							$('#investment_id').val(returns.response.data.investment_id);
							$('#installment_no').val(returns.response.data.installment_no);
							$('#total_installment').val(returns.response.data.total_installment);
							$('#interest_rate').val(returns.response.data.interest_rate);
							$('#period').val(returns.response.data.period);
							$('#amount').val(returns.response.data.ammount);
						} else {
							clearForm();
						}
					}
				});
			} else{
				clearForm();
			}
		}
		
		function clearForm(){
			$('#investment_id').val('');
			$('#installment_no').val('');
			$('#total_installment').val('');
			$('#interest_rate').val('');
			$('#period').val('');
			$('#amount').val('');
		}
	})
</script>