<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Members
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('members-new')?>" class="btn btn-primary">New Member</a>
			</span>
		</h3>
		<?php 
			if(!empty($this->flashMessages[0])) {
				foreach($this->flashMessages[0] as $class => $message) {
					echo '<div class="'.$class.'">'.$message.'</div>';	
				}
			}
			if ($this->error) {
				echo '<div class="error">'.$this->error.'</div>';	
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"><i class="fa fa-table fa-fw"></i> Members list</div>
			<!-- /.panel-heading -->
			<div class="panel-body table-responsive">
				<?php if(count($this->members) > 0): ?>
				<table class="table table-striped" style="word-wrap:break-word; table-layout:fixed;width:100%;">
					<thead>
						<tr>
							<td style="width: 7%;"><strong>#</strong></td>
							<td style="width: 20%;"><strong>Full Name</strong></td>
							<td style="width: 10%;"><strong>Member ID</strong></td>
							<td style="width: 16%;"><strong>Email</strong></td>
							<td style="width: 16%;"><strong>Mobile Number</strong></td>
							<td style="width: 15%;"><strong>Action</strong></td>
						</tr>
					</thead>
					<tbody>
					<?php $count = 1; foreach($this->members as $member): ?>
						<tr>
							<td><?php echo $count; ?></td>
							<td><?php echo ucwords($member->firstname.' '.$member->lastname); ?></td>
							<td><?php echo $member->member_id; ?></td>
							<td><?php echo $member->emailid; ?></td>
							<td><?php echo $member->mobile_number; ?></td>
							<td>
								<a title="Edit" href="<?php echo $this->basepath(); ?>/members/new/<?php echo $member->id; ?>" ><i class="glyphicon glyphicon-edit"></i></a> | 
								<a title="Delete" onclick="deleteMember('<?php echo $member->id; ?>')" href="javascript:void(0);"><i class="glyphicon glyphicon-remove-sign"></i></a>
							</td>
						</tr>
					<?php $count++; endforeach; ?>
					</tbody>
				</table>
				<?php else:?>
					<div class="text-center">No member found<div>
				<?php endif; ?>					
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->			
	</div>
	<!-- /.col-lg-12 -->		
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
	function deleteMember(memberId) {
		if(confirm('Are you sure for perform this action')) {
			window.location.href = '<?php echo $this->basepath(); ?>/delete/'+memberId;
		}
	}
</script>