<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Members
            <span class="job-btn pull-right">
                <a href="<?php echo $this->url('new-members') ?>" class="btn btn-primary">New Member</a>
            </span>
        </h3>		
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <?php echo $this->render('partials/flash-messages') ?>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-table fa-fw"></i> Members list</div>
            <!-- /.panel-heading -->
            <div class="panel-body table-responsive">
                <table id="member-table" class="table table-striped" style="word-wrap:break-word; table-layout:fixed;width:100%;">
                    <thead style="background: none repeat scroll 0 0 #313131;color: #fff;">
                        <tr>
                            <td style="width: 4%;"><strong>#</strong></td>
                            <td style="width: 10%;"><strong>Member ID</strong></td>
                            <td style="width: 13%;"><strong>Full Name</strong></td>							
                            <td style="width: 15%;"><strong>S/o, D/o, W/o</strong></td>
                            <td style="width: 10%;"><strong>Mobile Number</strong></td>
                            <td style="width: 15%;"><strong>Email</strong></td>							
                            <td style="width: 5%;"><strong>Action</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                    </tbody>
                </table>			
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->			
    </div>
    <!-- /.col-lg-12 -->		
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    $(document).ready(function () {
        $('#member-table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": '<?php echo $this->url('members') ?>',
            "bSort": false
        });
    }
    );
    function deleteMember(memberId) {
        if (confirm('Are you sure for perform this action')) {
            window.location.href = '<?php echo $this->basepath(); ?>/delete/' + memberId;
        }
    }
</script>