<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Member
			<!--<span class="job-btn pull-right">
				<a href="<?php echo $this->url('members')?>" class="btn btn-primary">Go Back</a>
			</span>-->
		</h3>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Register New Member
		</div>
		<div class="panel-body">
			<div class="row">
				<?php
					$form = $this->memberForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-6">						
					<div class="form-group">
						<label>First Name <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('firstname')); ?>
						<?php if($this->formElementErrors($form->get('firstname'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('firstname')))?></div>
						<?php endif;?>
						<?php echo $this->formElement($form->get('branch_id')); ?>
					</div>
					<div class="form-group">
						<label>Last Name</label>
						<?php echo $this->formElement($form->get('lastname')); ?>						
					</div>
					<div class="form-group">
						<label>S/o, D/o, W/o<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('gardian_name')); ?>
						<?php if($this->formElementErrors($form->get('gardian_name'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('gardian_name')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Email ID</label>
						<?php echo $this->formElement($form->get('emailid')); ?>
						<?php if($this->formElementErrors($form->get('emailid'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('emailid')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group date">
						<label>Date Of Birth <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('dob')); ?>
						<?php if($this->formElementErrors($form->get('dob'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('dob')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Gender <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('gender')); ?>
						<?php if($this->formElementErrors($form->get('gender'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('gender')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Address</label>
						<?php echo $this->formElement($form->get('address')); ?>
					</div>														
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Member Code <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('member_id')); ?>
					</div>
					<div class="form-group">
						<label>State <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('country_id')); ?>
						<?php echo $this->formElement($form->get('state_id')); ?>
						<?php if($this->formElementErrors($form->get('state_id'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('state_id')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>City</label>
						<?php echo $this->formElement($form->get('city_id')); ?>
					</div>
					<div class="form-group">
						<label>Mobile Number <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('mobile_number')); ?>
						<?php if($this->formElementErrors($form->get('mobile_number'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('mobile_number')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Nominee Name<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('nominee_name')); ?>
						<?php if($this->formElementErrors($form->get('nominee_name'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_name')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Nominee Relation<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('nominee_relation')); ?>
						<?php if($this->formElementErrors($form->get('nominee_relation'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_relation')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Nominee Address</label>
						<?php echo $this->formElement($form->get('nominee_address')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="clear"></div>
				<div class="col-lg-12">
					<div class="pull-right">
						<a href="<?php echo $this->url("members")?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
						<?php echo $this->formElement($form->get('save')); ?>								
					</div>							
				</div>
				<?php echo $this->form()->closeTag($form);?>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
					
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('#state_id').change(function() {
			stateId = $(this).val();
			getCities(stateId,'');	
		});	
		setTimeout(function(){
			getCities($('#state_id').val(), $('#city_id').val());
		}, 200);
		//$('#dob').datepicker({});
	})
	function getCities(stateid,cityid) {
		$.ajax({
			type: "POST",
			async:false,
			url: '<?php echo $this->basepath(); ?>/city',
			data: { 'stateid':stateid,'cityid':cityid },
			success: function(result) {
				var html = '<option value="">-Choose City-</option>';
				if(result.status) {					
					for(x in result.response.data) {
						if(result.response.data[x].selected) {
							html += '<option selected value="'+result.response.data[x].id+'">'+result.response.data[x].name+'</option>';
						} else {
							html += '<option value="'+result.response.data[x].id+'">'+result.response.data[x].name+'</option>';
						}
					}
				}
				$('#city_id').html(html);
			}
		});
	}
</script>