<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Member
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('members')?>" class="btn btn-primary">Go Back</a>
			</span>
		</h3>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Register New Member
		</div>
		<div class="panel-body">
			<div class="row">
				<?php
					$form = $this->memberForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
					<?php if (count($this->errors)) : ?>
						<div class="alert alert-danger">
							<?php foreach ($this->errors as $error) : ?>
							<?php if(is_array($error)) : echo current($error); else: echo $error;endif;?><br>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
					<div class="col-lg-6">						
						<div class="form-group">
							<label>First Name <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('firstname')); ?>
							<?php echo $this->formElement($form->get('branch_id')); ?>
						</div>
						<div class="form-group">
							<label>Last Name</label>
							<?php echo $this->formElement($form->get('lastname')); ?>
						</div>
						<div class="form-group">
							<label>S/o, D/o, W/o<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('gardian_name')); ?>
						</div>
						<div class="form-group">
							<label>Email ID</label>
							<?php echo $this->formElement($form->get('emailid')); ?>
						</div>
						<div class="form-group date">
							<label>Date Of Birth <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('dob')); ?>
						</div>
						<div class="form-group">
							<label>Gender <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('gender')); ?>
						</div>
						<div class="form-group">
							<label>Address</label>
							<?php echo $this->formElement($form->get('address')); ?>
						</div>														
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="col-lg-6">
						<div class="form-group">
							<label>Member Code <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('member_id')); ?>
						</div>
						<div class="form-group">
							<label>State <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('country_id')); ?>
							<?php echo $this->formElement($form->get('state_id')); ?>
						</div>
						<div class="form-group">
							<label>City</label>
							<?php echo $this->formElement($form->get('city_id')); ?>
						</div>
						<div class="form-group">
							<label>Mobile Number <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('mobile_number')); ?>
						</div>
						<div class="form-group">
							<label>Nominee Name<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('nominee_name')); ?>
						</div>
						<div class="form-group">
							<label>Nominee Relation<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('nominee_relation')); ?>
						</div>
						<div class="form-group">
							<label>Nominee Address<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('nominee_address')); ?>
						</div>
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="clear"></div>
					<div class="col-lg-12">
						<div class="pull-right">
							<a href="<?php echo $this->url("members")?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
							<?php echo $this->formElement($form->get('save')); ?>								
						</div>							
					</div>
				</form>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
					
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('#state_id').change(function() {
			stateId = $(this).val();
			getCities(stateId,'');	
		});
		<?php if($this->stateid): ?>
			getCities(<?php echo $this->stateid; ?>,<?php echo $this->cityid; ?>);
		<?php endif; ?>
		$('#dob').datepicker({});
	})
	function getCities(stateid,cityid) {
		$.ajax({
			type: "POST",
			async:false,
			url: '<?php echo $this->basepath(); ?>/city',
			data: { 'stateid':stateid,'cityid':cityid },
			success: function(cities) {
				$('#city_id').html(cities);
			}
		});
	}
</script>