<?php 
	echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
	echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
	echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
	echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>