<?php 
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) {
	?>
	<div class="alert flash-message">
		<?php 
			foreach ($flashMessage as $msg) { 
				foreach ($msg as $type => $message) {
					?>	
						<div class="<?php echo $type; ?>">
							<span><?php echo $message; ?></span>
						</div>
					<?php 
				} 
			}
		?>
	</div>
	<?php 
} 
if(isset($this->messages) && !empty($this->messages)) : ?>
<div class="alert flash-message">
	<?php foreach ($this->messages as $type => $msg) : ?>
		<div class="<?php echo $type; ?>">
			<span><?php echo $msg; ?></span>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>
<?php if(isset($this->errors) && !empty($this->errors)) : ?>
<div class="alert flash-message">
	<div class="error"><span>
	<?php foreach ($this->errors as $key => $error) {
			if(is_array($error)) {
				foreach ($error as $k => $errmsg) {
					echo $errmsg.'<br>';
				}					
			} else {
				echo $error;
			}
		}
	?>
	</span></div>
</div>
<?php endif; ?>