<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li class="sidebar-search">
				<div class="input-group custom-search-form">
					<input type="text" class="form-control" placeholder="Search...">
					<span class="input-group-btn">
					<button class="btn btn-default" type="button">
						<i class="fa fa-search"></i>
					</button>
				</span>
				</div>
			</li>
			<li>
				<a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
			</li>
			<li>
				<a href="#"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Members') ?><span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse">
					<li><a href="<?php echo $this->url('members')?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('All Members') ?></a></li>
					<li><a href="<?php echo $this->url('new-members')?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Add New Member') ?></a></li>
				</ul>
			</li>
			<li>
				<a href="#"><i class="fa fa-th-list fa-fw"></i> <?php echo $this->translate('Investments') ?><span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse">
					<li><a href="<?php echo $this->url('investors')?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('All Investors') ?></a></li>
					<li><a href="<?php echo $this->url('new-investors')?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Add New Investor') ?></a></li>
					<li><a href="<?php echo $this->url('new-installment')?>"><i class="fa fa-th-list fa-fw"></i> <?php echo $this->translate('Add New Installment') ?></a></li>
				</ul>
			</li>
			
			<li>
				<a href="#"><i class="fa fa-wrench fa-fw"></i>Manage Company<span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse">
					<li><a href="<?php echo $this->url('company-list') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Companies') ?></a></li>
					<li><a href="<?php echo $this->url('new-company') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('New Company') ?></a></li>
					<li><a href="<?php echo $this->url('branch-list') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Branches') ?></a></li>
					<li><a href="<?php echo $this->url('new-branch') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('New Branch') ?></a></li>
				</ul>
			</li>
			
			<li>
				<a href="#"><i class="fa fa-wrench fa-fw"></i>Manage Navigations<span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse">
					<li><a href="<?php echo $this->url('menu-list') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Menus') ?></a></li>
					<li><a href="<?php echo $this->url('new-menu') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('New Menu') ?></a></li>
				</ul>
			</li>
			
			<li>
				<a href="#"><i class="fa fa-wrench fa-fw"></i>Manage Employee<span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse">
					<li><a href="<?php echo $this->url('employee-list') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Employees') ?></a></li>
					<li><a href="<?php echo $this->url('new-employee') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('New Employee') ?></a></li>
					<li><a href="<?php echo $this->url('roles') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('Roles') ?></a></li>
					<li><a href="<?php echo $this->url('new-role') ?>"><i class="fa  fa-file-text fa-fw"></i> <?php echo $this->translate('New Role') ?></a></li>
				</ul>
			</li>
			
		</ul>
	</div>
</div>