<?php $user = $this->identity();?>
<div id="print">
	<div style="position:absolute;font-size: 18px;">
		<div class="name">
                    <?php echo $this->certificate->firstname.' '.$this->certificate->lastname?>
                    <?php if($this->certificate->dob) :?>
                        <?php $years = $this->ageinyears($this->certificate->dob, 'years')?>
                        <?php if($years > 18): ?>
                        (<?php echo $years?>)
                        <?php endif;?>
                    <?php endif;?>
                    <?php if($this->certificate->receipt_number) :?>    
                    <span style="float: right;margin-right: 316px;font-size: 18px;"><b>Rec No.: </b><?php echo $this->certificate->receipt_number?></span>  
                    <?php endif;?>
                </div>
		<div class="soname"><?php echo $this->certificate->gardian_name?></div>
		<div class="address"><?php echo $this->certificate->address?></div>
		<div class="ammount"><?php echo number_format($this->certificate->start_ammount,2)?>/- &nbsp;&nbsp;(Rupees <?php echo ucwords(\Application\Service\NumberToWords::toWords($this->certificate->start_ammount))?> Only)</div>
		<div class="member"><?php echo $this->certificate->member_id?></div>
		<div class="cfnumber"><?php echo $this->certificate->cf_number?></div>
		<div class="startdate"><?php echo date('M d, Y',strtotime($this->certificate->start_date))?></div>
		<div class="period"><?php echo $this->certificate->period?></div>
		<div class="interest"><?php echo $this->certificate->interest_rate?> %</div>
		<div class="maturity"><?php echo date('M d, Y',strtotime($this->certificate->end_date))?></div>
		<div class="nomenee"><?php echo $this->certificate->nominee_name?> (<?php echo $this->certificate->nominee_relation?>)</div>
		<div class="repay"><?php echo ucfirst($this->certificate->repayable_to)?></div>
		<div class="dob">&nbsp;
                    <?php if($this->certificate->dob) :?>
                        <?php if($years <=18): ?>
                        <?php echo date('M d, Y',strtotime($this->certificate->dob))?>
                        <?php endif;?>
                    <?php endif;?>                    
                </div>
		<div class="mode"><?php echo ucfirst($this->certificate->installment_type)?></div>
		<div class="installmentdate"><?php echo ucfirst($this->certificate->installment_date)?></div>
		<div class="lastinstallmentdate"><?php echo date('M d, Y',strtotime($this->certificate->last_installment_date))?></div>
		<div class="final"><?php echo number_format($this->certificate->final_ammount, 2)?>/- &nbsp;&nbsp;(Rupees <?php echo ucwords(\Application\Service\NumberToWords::toWords($this->certificate->final_ammount))?> Only)</div>
		<div class="prentedby"><?php echo $user->firstname?> <?php echo $user->lastname?>
                    <?php if(isset($user->branch->code)) :?>
                    (<?php echo $user->branch->code?>)
                    <?php endif;?>
                </div>
                <div class="agentcode"><?php echo $this->certificate->employee_code?></div>
                
	</div>
	<style type="text/css">
		body{
			overflow-y: scroll;
			overflow-x: hidden;
		}
		@page{
			size: auto A4 landscape;
			margin: 3mm;
		}
		#print{
			background-image : url('<?php echo $this->basePath('img/certificate.jpg')?>');
			background-repeat: no-repeat;
			/*
                        background-position: center center;    
                        background-attachment: fixed;*/
			background-size: contain;			
			width:100%;
			height:755px;			
		}
		.name{
			margin:163px 0 0 256px;
			width:100%;
			font-size: 19px;
		}
		
		.soname{
			margin:0 0 0 256px;
			width:100%;
			font-size: 19px;
		}
		.address{
			margin:0 0 0 256px;
			width:100%;
			font-size: 19px;
		}
		.ammount{
			margin:32px 0 0 256px;
			width:100%;
			font-size: 19px;
		}
		.member{
			margin:75px 0 0 26px;
			width:14%;
		}
		.cfnumber{
			margin:-24px 0 0 223px;
			width:15%;
			white-space: nowrap;
		}
		.startdate{
			margin:-26px 0 0 364px;
			width:11%;
		}
		.period{
			margin:-25px 0 0 485px;
			width:9%;
		}
		.interest{
			margin:-25px 0 0 616px;
			width:7%;
		}
		.maturity{
			margin:-25px 0 0 683px;
			width:11%;
		}
		.nomenee{
			margin:-25px 0 0 795px;
			width:22%;
                        height: 24px;
                        line-height: 24px;
		}
		.repay{
			margin: 56px 0 0 156px;
			width: 22%;
		}
		.dob{
			margin: -26px 0 0 824px;
			width: 22%;
		}
		.mode{
			margin: 16px 0 0 211px;
			width: 22%;
		}
		.installmentdate{
			margin: -36px 0 0 493px;
			width: 22%;
			font-size: 14px;
                        height:40px;
                        line-height: 21px;
		}
		.lastinstallmentdate{
			margin: -30px 0 0 868px;
			width: 22%;
		}
		.final{
			margin: 10px 0 0 207px;
			width: 87%;
		}
		.prentedby{
			margin: 25px 0 0 211px;
			width: 87%;
		}
		.agentcode{
			margin: -26px 0 0 838px;
			width: 87%;
		}
		.btn {
			-moz-user-select: none;
			background-image: none;
			border: 1px solid transparent;
			border-radius: 4px;
			cursor: pointer;
			display: inline-block;
			font-size: 14px;
			font-weight: 400;
			line-height: 1.42857;
			margin-bottom: 0;
			padding: 6px 12px;
			text-align: center;
			vertical-align: middle;
			white-space: nowrap;
			text-decoration:none;
		}
		.btn-primary {
			background-color: #337ab7;
			border-color: #2e6da4;
			color: #fff;
		}
		.btn-success {
			background-color: #5cb85c;
			border-color: #4cae4c;
			color: #fff;
		}
	</style>
</div>
<div style="padding:10px 10px;text-align:center;">	
	<a class="btn btn-primary" href="<?php echo $this->url('investors');?>">Go Back</a>
	<a class="btn btn-success" style="margin:0 10px;" target="_blank" href="<?php echo $this->url('print-certificate', array('id'=>$this->id));?>">Print</a>
</div>
<script type="text/javascript">
	jQuery(document).bind("keyup keydown", function(e){
		if(e.ctrlKey && e.keyCode == 80){
			window.open(
			  '<?php echo $this->url('print-certificate', array('id'=>$this->id));?>',
			  '_blank' // <- This is what makes it open in a new window.
			);
			//window.location.href = '<?php echo $this->url('print-certificate', array('id'=>$this->id));?>';
			return false;
		}
	});
</script>