<?php $user = $this->identity();?>
<div id="print">
	<div style="position:absolute;font-size: 21px;">
		<div class="name">
                    <?php echo $this->certificate->firstname.' '.$this->certificate->lastname?>
                    <?php if($this->certificate->dob) :?>
                        <?php $years = $this->ageinyears($this->certificate->dob, 'years')?>
                        <?php if($years > 18): ?>
                        (<?php echo $years?>)
                        <?php endif;?>
                    <?php endif;?>
                </div>
		<div class="soname"><?php echo $this->certificate->gardian_name?></div>
		<div class="address"><?php echo $this->certificate->address?></div>
		<div class="ammount"><?php echo number_format($this->certificate->start_ammount,2)?>/- &nbsp;&nbsp;(Rupees <?php echo ucwords(\Application\Service\NumberToWords::toWords($this->certificate->start_ammount))?> Only)</div>
		<div class="member"><?php echo $this->certificate->member_id?></div>
		<div class="cfnumber"><?php echo $this->certificate->cf_number?></div>
		<div class="startdate"><?php echo date('M d, Y',strtotime($this->certificate->start_date))?></div>
		<div class="period"><?php echo $this->certificate->period?></div>
		<div class="interest"><?php echo $this->certificate->interest_rate?> %</div>
		<div class="maturity"><?php echo date('M d, Y',strtotime($this->certificate->end_date))?></div>
		<div class="nomenee"><?php echo $this->certificate->nominee_name?> (<?php echo $this->certificate->nominee_relation?>)</div>
		<div class="repay"><?php echo ucfirst($this->certificate->repayable_to)?></div>
		<div class="dob">&nbsp;
                    <?php if($this->certificate->dob) :?>
                        <?php if($years <=18): ?>
                            <?php echo date('M d, Y',strtotime($this->certificate->dob))?>
                        <?php endif;?>
                    <?php endif;?> 
                </div>
		<div class="mode"><?php echo ucfirst($this->certificate->installment_type)?></div>
		<div class="installmentdate"><?php echo ucfirst($this->certificate->installment_date)?></div>
		<div class="lastinstallmentdate"><?php echo date('M d, Y',strtotime($this->certificate->last_installment_date))?></div>
		<div class="final"><?php echo number_format($this->certificate->final_ammount, 2)?>/- &nbsp;&nbsp;(Rupees <?php echo ucwords(\Application\Service\NumberToWords::toWords($this->certificate->final_ammount))?> Only)</div>
		<div class="prentedby"><?php echo $user->first_name?> <?php echo $user->last_name?>
                    <?php if(isset($user->employee_code)) :?>
                        (<?php echo $user->employee_code?>)
                    <?php endif;?>
                </div>
                <div class="agentcode"><b>Agent Code</b>:<?php echo $this->certificate->employee_code?></div>
	</div>
	<style type="text/css">
		body{
			overflow-y: scroll;
			overflow-x: hidden;
		}
		@page{
			size: auto A4 landscape;
			margin: 3mm;
		}
		#print{
			width:100%;
			height:948px;			
		}
		.name{
			margin:314px 0 0 450px;
			width:100%;
			font-size: 23px;
		}
		.soname{
			margin:11px 0 0 450px;
			width:100%;
			font-size: 23px;
		}
		.address{
			margin:14px 0 0 450px;
			width:100%;
			font-size: 23px;
		}
		.ammount{
			margin:54px 0 0 450px;
			width:100%;
			font-size: 23px;
		}
		.member{
			margin:96px 0 0 208px;
			width:14%;
		}
		.cfnumber{
			margin:-24px 0 0 409px;
			width:15%;
			white-space: nowrap;
		}
		.startdate{
			margin:-24px 0 0 618px;
			width:11%;
		}
		.period{
			margin:-25px 0 0 786px;
			width:9%;
		}
		.interest{
			margin:-24px 0 0 954px;
			width:7%;
		}
		.maturity{
			margin:-24px 0 0 1055px;
			width:11%;
		}
		.nomenee{
			margin:-24px 0 0 1230px;
			width:22%;
                        white-space: nowrap;
		}
		.repay{
			margin: 108px 0 0 300px;
			width: 22%;
		}
		.dob{
			margin: -12px 0 0 1210px;
			width: 22%;
		}
		.mode{
			margin: 16px 0 0 378px;
			width: 22%;
		}
		.installmentdate{
			margin: -22px 0 0 778px;
			width: 22%;
			font-size: 18px;
                        white-space: nowrap;
		}
		.lastinstallmentdate{
			margin: -16px 0 0 1305px;
			width: 22%;
		}
		.final{
			margin: 15px 0 0 359px;
			width: 87%;
		}
		.prentedby{
			margin: 45px 0 0 413px;
			width: 87%;
		}
                .agentcode{
			margin: -26px 0 0 1101px;
			width: 87%;
		}
		.btn {
			-moz-user-select: none;
			background-image: none;
			border: 1px solid transparent;
			border-radius: 4px;
			cursor: pointer;
			display: inline-block;
			font-size: 14px;
			font-weight: 400;
			line-height: 1.42857;
			margin-bottom: 0;
			padding: 6px 12px;
			text-align: center;
			vertical-align: middle;
			white-space: nowrap;
			text-decoration:none;
		}
		.btn-primary {
			background-color: #337ab7;
			border-color: #2e6da4;
			color: #fff;
		}
		.btn-success {
			background-color: #5cb85c;
			border-color: #4cae4c;
			color: #fff;
		}
	</style>
</div>
<script type="text/javascript">
	jQuery(document).ready(function(e){
		var printContents = document.getElementById('print').innerHTML;
		var originalContents = document.body.innerHTML;
		document.body.innerHTML = printContents;
		window.print();
		document.body.innerHTML = originalContents;
		//window.close();
	});
</script>

