<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Investors List
            <span class="job-btn pull-right">
                <a href="<?php echo $this->url('new-investors')?>" class="btn btn-primary">New Investor</a>
            </span>
        </h3>
    </div>
</div>

<div class="row">
    <?php echo $this->render('partials/flash-messages')?>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-table fa-fw"></i> Investors Table</div>
            <!-- /.panel-heading -->
            <div class="panel-body table-responsive">
                <table id="investor-table" class="table table-striped" style="word-wrap:break-word; table-layout:fixed;width:100%;">
                    <thead style="background: none repeat scroll 0 0 #313131;color: #fff;">
                        <tr>
                            <th style="width: 7%;"><strong>#</strong></th>
                            <th style="width: 18%;"><strong>CF Number</strong></th>
                            <th style="width: 17%;"><strong>Employee Code</strong></th>
                            <th style="width: 18%;"><strong>Full Name</strong></th>
                            <th style="width: 16%;"><strong>Member ID</strong></th>                                               
                            <th style="width: 13%;"><strong>Mat. Amt</strong></th>
                            <th style="width: 14%;"><strong>Mat. Date</strong></th>
                            <th style="width: 12%;" class="text-center"><strong>Action</strong></th>
                        </tr>
                    </thead>
                    <tbody style="border-bottom: 3px solid #313131;">
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
        $(document).ready(function() {
            $('#investor-table').DataTable( {
                "processing": true,
                "serverSide": true,
                "ajax": '<?php echo $this->url('investors')?>',
                "bSort" : false
            } );
        } );
	function deleteMember(memberId) {
		if(confirm('Are you sure for perform this action')) {
			window.location.href = '<?php echo $this->basepath(); ?>/delete/'+memberId;
		}
	}
</script>