<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Investor</h3>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Member Investments
		</div>
		<div class="panel-body">
			<div class="row">
				<?php
					$form = $this->investorForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-6">		
					<div class="form-group">
						<label>Member Code <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('member_id')); ?>
						<?php if($this->formElementErrors($form->get('member_id'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('member_id')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">								
						<label>Name <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('name')); ?>
						<?php echo $this->formElement($form->get('branch_id')); ?>
					</div>
					<div class="form-group">
						<label>S/o, D/o, W/o<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('gardian_name')); ?>
					</div>
					<div class="form-group">
						<label>Email ID</label>
						<?php echo $this->formElement($form->get('emailid')); ?>
					</div>
					<div class="form-group">
						<label>Mobile Number</label>
						<?php echo $this->formElement($form->get('mobile_number')); ?>
					</div>
					<div class="form-group">
						<label>Nominee Name</label>
						<?php echo $this->formElement($form->get('nominee_name')); ?>
					</div>
					<div class="form-group">
						<label>Nominee Relation</label>
						<?php echo $this->formElement($form->get('nominee_relation')); ?>
					</div>
					<div class="form-group">
						<label>Address</label>
						<?php echo $this->formElement($form->get('address')); ?>
					</div>														
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">	
					<div class="form-group">
						<label>Plan</label>
						<?php echo $this->formElement($form->get('plan_id')); ?>
						<?php if($this->formElementErrors($form->get('plan_id'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('plan_id')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Plan Maturity Time</label>
						<?php echo $this->formElement($form->get('duration')); ?>
						<?php if($this->formElementErrors($form->get('duration'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('duration')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Installment Type</label>
						<?php echo $this->formElement($form->get('installment_type')); ?>
						<?php if($this->formElementErrors($form->get('installment_type'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('installment_type')))?></div>
						<?php endif;?>
					</div>						
					<div class="form-group">
						<label>Deposite Amount</label>
						<?php echo $this->formElement($form->get('start_ammount')); ?>
						<?php if($this->formElementErrors($form->get('start_ammount'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('start_ammount')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Interest Rate</label>
						<?php echo $this->formElement($form->get('interest_rate')); ?>
						<?php if($this->formElementErrors($form->get('interest_rate'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('interest_rate')))?></div>
						<?php endif;?>
					</div>		
					<div class="form-group">
						<label>Installment Amount</label>
						<?php echo $this->formElement($form->get('installment_ammount')); ?>
						<?php if($this->formElementErrors($form->get('installment_ammount'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('installment_ammount')))?></div>
						<?php endif;?>
					</div>	
					<div class="form-group">
						<label>Installment Date</label>
						<?php echo $this->formElement($form->get('installment_date')); ?>
						<?php if($this->formElementErrors($form->get('installment_date'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('installment_date')))?></div>
						<?php endif;?>
					</div>
					<div class="form-group">
						<label>Maturity Amount</label>
						<?php echo $this->formElement($form->get('final_ammount')); ?>
						<?php if($this->formElementErrors($form->get('final_ammount'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('final_ammount')))?></div>
						<?php endif;?>
					</div>							
					<div class="form-group">
						<label>Maturity Date</label>
						<?php echo $this->formElement($form->get('start_date')); ?>
						<?php echo $this->formElement($form->get('end_date')); ?>
						<?php if($this->formElementErrors($form->get('end_date'))) :?>
						<div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('end_date')))?></div>
						<?php endif;?>
					</div>							
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="clear"></div>
				<div class="col-lg-12">
					<div class="pull-right">
						<a href="<?php echo $this->url("investors")?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
						<?php echo $this->formElement($form->get('save')); ?>								
					</div>							
				</div>
				<?php echo $this->form()->closeTag($form);?>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
					
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('#member_id').keyup(function() {
			member = $(this).val();
			memberDetsils(member);	
		});
		memberDetsils($('#member_id').val());	
		$('#plan_id').change(function() {
			paln = $(this).val();
			if(paln) {
				clearPlan();
				$.ajax({
					url : '<?php echo $this->basePath('apis/plan-durations')?>',
					type:'post',
					data:{id:paln},
					success:function(returns) {
						if(returns.status) {
							html = '<option value="">-Choose Plan Maturity Time-</option>';
							for(x in returns.response.data) {
								if(returns.response.data[x].duration_type == 'M') {
									html += '<option value="'+returns.response.data[x].duration+'">'+returns.response.data[x].duration+' (Months) </option>';			
								}
								if(returns.response.data[x].duration_type == 'D') {
									html += '<option value="'+returns.response.data[x].duration+'">'+returns.response.data[x].duration+' (Days) </option>';		
								}
							}
							$('#duration').html(html);
						} else {
							$('#duration').html('<option value="">-Choose Plan Maturity Time-</option>');	
						}
					}
				});
			} else{
				$('#duration').html('<option value="">-Choose Plan Maturity Time-</option>');
				clearPlan();
			}	
		});	
		
		$('#duration').change(function() {
			duration = $(this).val();
			if(duration) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/plan-installments')?>',
					type:'post',
					data:{id:$('#plan_id').val(),duration:duration},
					success:function(returns) {
						if(returns.status) { 
							html = '<option value="">-Choose Installment Type-</option>';
							for(x in returns.response.data) {
								html += '<option value="'+returns.response.data[x].id+'">'+returns.response.data[x].installment_type+'</option>';											
							}
							$('#installment_type').html(html);
						} 
					}
				});
			} else{
				$('#installment_type').html('<option value="">-Choose Installment Type-</option>');
				$('#interest_rate').val('');
			}	
		});	
		
		$('#installment_type').change(function() {
			installment  =  $(this).val();
			if(installment) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/plan-ammounts')?>',
					type:'post',
					data:{id:installment},
					success:function(returns) {
						if(returns.status) { 
							html = '<option value="">-Choose Deposite Amount-</option>';
							for(x in returns.response.data) {
								html += '<option value="'+returns.response.data[x].id+'">'+returns.response.data[x].deposit_amount+'</option>';			
							}
							$('#start_ammount').html(html);
						} else {
							$('#start_ammount').val('<option value="">-Choose Amount-</option>');
						}
					}
				});
			}	
		});
			
		$('#start_ammount').change(function() {
			formulaid  =  $(this).val();
			if(formulaid) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/plan-ammounts-details')?>',
					type:'post',
					data:{id:formulaid},
					success:function(returns) {
						$('#interest_rate').val(returns.response.data.interest_rate);
						$('#installment_ammount').val(returns.response.data.amount);
						$('#final_ammount').val(returns.response.data.maturity_ammount);
						$('#installment_date').val(returns.response.installment_date);
						$('#end_date').val(returns.response.end_date);
					}
				});
			} else {
				
			}	
		});
			
		
		function clearPlan() {
			$('#start_ammount').html('<option value="">-Choose Deposite Amount-</option>')
			$('#final_ammount').val('');
			$('#installment_ammount').val('');
			$('#end_date').val('');
			$('#interest_rate').val('');
		}
		
		function memberDetsils(member) {
			if(member) {
				$.ajax({
					url : '<?php echo $this->basePath('apis/member')?>',
					type:'post',
					data:{code:member},
					success:function(returns) {
						if(returns.status) {
							$('#name').val(returns.response.data.firstname+' '+returns.response.data.lastname);
							$('#gardian_name').val(returns.response.data.gardian_name);
							$('#emailid').val(returns.response.data.emailid);
							$('#address').val(returns.response.data.address);	
							$('#mobile_number').val(returns.response.data.mobile_number);	
							$('#nominee_name').val(returns.response.data.nominee_name);	
							$('#nominee_relation').val(returns.response.data.nominee_relation);	
						} else {
							$('#name').val('');
							$('#gardian_name').val('');
							$('#emailid').val('');
							$('#mobile_number').val('');
							$('#address').val('');	
							$('#nominee_name').val('');	
							$('#nominee_relation').val('');	
						}
					}
				});
			} else{
				$('#name').val('');
				$('#gardian_name').val('');
				$('#emailid').val('');
				$('#address').val('');
				$('#nominee_name').val('');
			}			
		}
	})
</script>