<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('EPG '. $this->translate('Services Login'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .'/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('components/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('components/metisMenu/dist/metisMenu.min.css'))
                        ->prependStylesheet($this->basePath('components/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/admin.js'))
           /** Morris Charts JavaScript **/
           ->prependFile($this->basePath('components/metisMenu/dist/metisMenu.min.js'))
			/** Bootstrap **/
            ->prependFile($this->basePath('components/bootstrap/dist/js/bootstrap.min.js'))
			/** JQuery and Html5 Shiv **/
            ->prependFile($this->basePath('components/jquery/dist/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
