<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Employee
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('employee-list')?>" class="btn btn-primary">Employee List</a>
			</span>
		</h3>
		<?php 
			if(!empty($this->flashMessages[0])) {
				foreach($this->flashMessages[0] as $class => $message) {
					echo '<div class="'.$class.'">'.$message.'</div>';	
				}
			}
			if ($this->error) {
				echo '<div class="error">'.$this->error.'</div>';	
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<?php
	$form = $this->employeeForm;
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Employee Personal Information Section
		</div>
		<div class="panel-body">
			<div class="row">
					<?php if (count($this->errors)) : ?>
						<div class="alert alert-danger">
							<?php foreach ($this->errors as $error) : ?>
							<?php if(is_array($error)) : echo current($error); else: echo $error;endif;?><br>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
					<div class="col-lg-6">						
						<div class="form-group">
							<label>First Name <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('first_name')); ?>
						</div>							
						<div class="form-group">
							<label>Phone Number <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('phone_no')); ?>
						</div>
						<div class="form-group">
							<label>Father Name<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('father_name')); ?>
						</div>
						<div class="form-group">
							<label>Email Id <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('emailid')); ?>
						</div>
						<div class="form-group">
							<label>Company<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('company_id')); ?>
						</div>
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="col-lg-6">
						<div class="form-group">
							<label>Last Name <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('last_name')); ?>
						</div>
						<div class="form-group">
							<label>Mobile Number <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('mobile_no')); ?>
						</div>
						<div class="form-group">
							<label>Mother Name<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('mother_name')); ?>
						</div>
						<div class="form-group">
							<label>Spouse <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('spouse')); ?>
						</div>
						<div class="form-group">
							<label>Branch <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('branch_id')); ?>
						</div>
					</div>
				</form>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
		  
	<div class="panel panel-default">
		<div class="panel-heading">
			Employee Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Address <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('address')); ?>
					</div>							
					<div class="form-group">
						<label>City <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('city')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Country <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('country_id')); ?>
					</div>
					<div class="form-group">
						<label>State <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('state_id')); ?>
					</div>
					<div class="form-group">
						<label>Pincode<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('pincode')); ?>
					</div>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>	
	
	<div class="panel panel-default">
		<div class="panel-heading">
			Employee Permanent Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Address <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_address')); ?>
					</div>							
					<div class="form-group">
						<label>City <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_city')); ?>
					</div>
					<div class="form-group">
						<label>Phone Number <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_phoneno')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Country <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_country_id')); ?>
					</div>
					<div class="form-group">
						<label>State <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_state_id')); ?>
					</div>
					<div class="form-group">
						<label>Pincode<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_pincode')); ?>
					</div>
					<div class="form-group">
						<label>Mobile Number <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_mobileno')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="clear"></div>						
				<div class="col-lg-6">
					<?php echo $this->formElement($form->get('save-employee')); ?>
					<?php echo $this->formElement($form->get('reset')); ?>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
</div>