<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">New Employee
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('employee-list')?>" class="btn btn-primary">Employee List</a>
			</span>
		</h1>
		<?php 
			if(!empty($this->flashMessages[0])) {
				foreach($this->flashMessages[0] as $class => $message) {
					echo '<div class="'.$class.'">'.$message.'</div>';	
				}
			}
			if ($this->error) {
				echo '<div class="error">'.$this->error.'</div>';	
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<?php
	$form = $this->employeeForm;
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Personal Information Section
		</div>
		<div class="panel-body">
			<div class="row">
					<?php if (count($this->errors)) : ?>
						<div class="alert alert-danger">
							<?php foreach ($this->errors as $error) : ?>
							<?php if(is_array($error)) : echo current($error); else: echo $error;endif;?><br>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
					<div class="col-lg-6">						
						<div class="form-group">
							<label>First Name <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('first_name')); ?>
						</div>							
						<div class="form-group">
							<label>Phone Number <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('phone_no')); ?>
						</div>
						<div class="form-group">
							<label>Father Name<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('father_name')); ?>
						</div>
						<div class="form-group">
							<label>Email Id <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('email_id')); ?>
						</div>
						<div class="form-group">
							<label>Company<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('company_id')); ?>
						</div>
						<div class="form-group">
							<label>Blood Group<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('blood_group')); ?>
						</div>
						<div class="form-group">
							<label>Photo<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('photo')); ?>
						</div>
					</div>
					<!-- /.col-lg-6 (nested) -->
					<div class="col-lg-6">
						<div class="form-group">
							<label>Last Name <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('last_name')); ?>
						</div>
						<div class="form-group">
							<label>Mobile Number <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('mobile_no')); ?>
						</div>
						<div class="form-group">
							<label>Mother Name<span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('mother_name')); ?>
						</div>
						<div class="form-group">
							<label>Spouse Name</label>
							<?php echo $this->formElement($form->get('spouse_name')); ?>
						</div>
						<div class="form-group">
							<label>Branch <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('branch_id')); ?>
						</div>
						<div class="form-group">
							<label>Status <span class="mandatory">*</span></label>
							<?php echo $this->formElement($form->get('status')); ?>
						</div>
					</div>
				</form>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
		  
	<div class="panel panel-default">
		<div class="panel-heading">
			Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Address <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('address')); ?>
					</div>							
					<div class="form-group">
						<label>City <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('city')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Country <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('country_id')); ?>
					</div>
					<div class="form-group">
						<label>State <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('state_id')); ?>
					</div>
					<div class="form-group">
						<label>Pincode<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('pincode')); ?>
					</div>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>	
	
	<div class="panel panel-default">
		<div class="panel-heading">
			Permanent Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Address <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_address')); ?>
					</div>							
					<div class="form-group">
						<label>City <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_city')); ?>
					</div>
					<div class="form-group">
						<label>Phone Number <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_phoneno')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Country <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_country_id')); ?>
					</div>
					<div class="form-group">
						<label>State <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_state_id')); ?>
					</div>
					<div class="form-group">
						<label>Pincode<span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_pincode')); ?>
					</div>
					<div class="form-group">
						<label>Mobile Number <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('per_mobileno')); ?>
					</div>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			Education Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Certificate <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('certificate')); ?>
					</div>							
					<div class="form-group">
						<label>University <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('university')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>Year <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('year')); ?>
					</div>
					<div class="form-group">
						<label>Percentage <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('percentage')); ?>
					</div>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			Work Experience Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Previous Employer <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('previous_employer')); ?>
					</div>							
					<div class="form-group">
						<label>Designation <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('designation')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
						<label>From <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('employee_from')); ?>
					</div>
					<div class="form-group">
						<label>To <span class="mandatory">*</span></label>
						<?php echo $this->formElement($form->get('employee_to')); ?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="clear"></div>						
				<div class="col-lg-6">
					<?php echo $this->formElement($form->get('save-employee')); ?>
					<?php echo $this->formElement($form->get('reset')); ?>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
	
</div>
<!-- /.row -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('#country_id').change(function() {
			countryId = $(this).val();
			getStates(countryId,'');
		});
		countryId = $('#country_id').val();
		if(countryId) {
			getStates(countryId,"<?php echo $this->stateid; ?>");
		}
		
		$('#per_country_id').change(function() {
			perCountryId = $(this).val();
			getPerStates(perCountryId,'');
		});
		perCountryId = $('#per_country_id').val();
		if(perCountryId) {
			getPerStates(perCountryId,"<?php echo $this->stateid; ?>");
		}
		
		$('#company_id').change(function() {
			companyId = $(this).val();
			getBranches(companyId,'');
		});
		companyId = $('#company_id').val();
		if(companyId) {
			getBranches(companyId,"<?php echo $this->branchid; ?>");
		}
	});	
</script>