<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">New Agent</h1>
    </div>
</div>

<?php
	$form = $this->employeeForm;
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			Personal Information Section
		</div>
		<div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">						
                            <div class="form-group">
                                <label>Name <span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('employee_name')); ?>
                                <?php if($this->formElementErrors($form->get('employee_name'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('employee_name')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Mobile Number <span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('mobile_no')); ?>
                                <?php if($this->formElementErrors($form->get('mobile_no'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('mobile_no')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Father Name<span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('father_name')); ?>
                                <?php if($this->formElementErrors($form->get('father_name'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('father_name')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Mother Name<span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('mother_name')); ?>
                                <?php if($this->formElementErrors($form->get('mother_name'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('mother_name')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Nominee Name<span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('nominee_name')); ?>
                                <?php if($this->formElementErrors($form->get('nominee_name'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_name')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Nominee Relation<span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('nominee_relation')); ?>
                                <?php if($this->formElementErrors($form->get('nominee_relation'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_relation')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Nominee Address</label>
                                <?php echo $this->formElement($form->get('nominee_address')); ?>
                                <?php if($this->formElementErrors($form->get('nominee_address'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_address')))?></div>
                                <?php endif;?>
                            </div>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                        <div class="col-lg-6">
                            
                            <div class="form-group">
                                <label>Email Id</label>
                                <?php echo $this->formElement($form->get('email')); ?>
                                <?php if($this->formElementErrors($form->get('email'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('email')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Pan Number</label>
                                <?php echo $this->formElement($form->get('pan_number')); ?>
                                <?php if($this->formElementErrors($form->get('pan_number'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('pan_number')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Company<span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('company_id')); ?>
                                <?php if($this->formElementErrors($form->get('company_id'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('company_id')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Branch <span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('branch_id')); ?>
                                <?php if($this->formElementErrors($form->get('branch_id'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('branch_id')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Role <span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('role_id')); ?>
                                <?php if($this->formElementErrors($form->get('role_id'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('role_id')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Introducer Name</label>
                                <?php echo $this->formElement($form->get('introducer_code')); ?>
                                <?php if($this->formElementErrors($form->get('introducer_code'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('introducer_code')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Blood Group</label>
                                <?php echo $this->formElement($form->get('blood_group')); ?>
                                <?php if($this->formElementErrors($form->get('blood_group'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('blood_group')))?></div>
                                <?php endif;?>
                            </div>
                            <div class="form-group">
                                <label>Status <span class="mandatory">*</span></label>
                                <?php echo $this->formElement($form->get('status')); ?>
                                <?php if($this->formElementErrors($form->get('status'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('status')))?></div>
                                <?php endif;?>
                            </div>						
                            <div class="form-group">
                                <label>Photo</label>
                                <?php echo $this->formElement($form->get('photo')); ?>
                                <?php if($this->formElementErrors($form->get('photo'))) :?>
                                <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('photo')))?></div>
                                <?php endif;?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
	</div>
		  
	<div class="panel panel-default" id="login-section">
		<div class="panel-heading">
			Login Credentials Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">
					<div class="form-group">
                                            <label>User Id</label>
                                            <?php echo $this->formElement($form->get('user_id')); ?>
                                            <?php if($this->formElementErrors($form->get('user_id'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('user_id')))?></div>
                                            <?php endif;?>
					</div>
					<div class="form-group">
                                            <label>Code</label>
                                            <?php echo $this->formElement($form->get('employee_code')); ?>
                                            <?php if($this->formElementErrors($form->get('employee_code'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('employee_code')))?></div>
                                            <?php endif;?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
					<div class="form-group">
                                            <label>Password</label>
                                            <?php echo $this->formElement($form->get('password')); ?>
                                            <?php if($this->formElementErrors($form->get('password'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('password')))?></div>
                                            <?php endif;?>
					</div>
					<div class="form-group">
                                            <label>Confirm Password</label>
                                            <?php echo $this->formElement($form->get('cpassword')); ?>
                                            <?php if($this->formElementErrors($form->get('cpassword'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('cpassword')))?></div>
                                            <?php endif;?>
					</div>
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>	
	<div class="panel panel-default">
		<div class="panel-heading">
			Permanent Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
                                            <label>Address <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('per_address')); ?>
                                            <?php if($this->formElementErrors($form->get('per_address'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('per_address')))?></div>
                                            <?php endif;?>
					</div>
                                        <div class="form-group">
                                            <label>Mobile Number <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('per_mobile_no')); ?>
                                            <?php if($this->formElementErrors($form->get('per_mobile_no'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('per_mobile_no')))?></div>
                                            <?php endif;?>
					</div>
					<div class="form-group">
                                            <label>Country <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('per_country_id')); ?>
                                            <?php if($this->formElementErrors($form->get('per_country_id'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('per_country_id')))?></div>
                                            <?php endif;?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">					
					<div class="form-group">
                                            <label>State <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('per_state_id')); ?>
                                            <?php if($this->formElementErrors($form->get('father_name'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('father_name')))?></div>
                                            <?php endif;?>
					</div>
                                        <div class="form-group">
                                            <label>City <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('per_city')); ?>
                                            <?php if($this->formElementErrors($form->get('per_city'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('per_city')))?></div>
                                            <?php endif;?>
					</div>
					<div class="form-group">
                                            <label>Pincode</label>
                                            <?php echo $this->formElement($form->get('per_pincode')); ?>
                                            <?php if($this->formElementErrors($form->get('per_pincode'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('per_pincode')))?></div>
                                            <?php endif;?>
					</div>
					
				</div>				
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>
    
	<div class="panel panel-default">
		<div class="panel-heading">
			Mailing Address Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
                                            <label>Address <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('address')); ?>
                                            <?php if($this->formElementErrors($form->get('address'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('address')))?></div>
                                            <?php endif;?>
					</div>							
					<div class="form-group">
                                            <label>Country <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('country_id')); ?>
                                            <?php if($this->formElementErrors($form->get('country_id'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('country_id')))?></div>
                                            <?php endif;?>
					</div>
				</div>
				<!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">					
					<div class="form-group">
                                            <label>State <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('state_id')); ?>
                                            <?php if($this->formElementErrors($form->get('state_id'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('state_id')))?></div>
                                            <?php endif;?>
					</div>
                                        <div class="form-group">
                                            <label>City <span class="mandatory">*</span></label>
                                            <?php echo $this->formElement($form->get('city')); ?>
                                            <?php if($this->formElementErrors($form->get('city'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('city')))?></div>
                                            <?php endif;?>
					</div>
					<div class="form-group">
                                            <label>Pincode</label>
                                            <?php echo $this->formElement($form->get('pincode')); ?>
                                            <?php if($this->formElementErrors($form->get('pincode'))) :?>
                                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('pincode')))?></div>
                                            <?php endif;?>
					</div>
				</div>
                                <div class="clear"></div>						
				<div class="col-lg-12">
                                    <div class="col-lg-6"></div>
                                    <div class="col-lg-6 text-right">
                                        <a href="<?php echo $this->basePath()?>" class="btn btn-default">Back</a>&nbsp;&nbsp;&nbsp;
                                        <?php echo $this->formElement($form->get('save-employee')); ?>
                                    </div>                                    
				</div>
			</div>
			<!-- /.row (nested) -->
		</div>
		<!-- /.panel-body -->
	</div>	
	
	<!--
	<div class="panel panel-default">
		<div class="panel-heading">
			Education Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Certificate <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('certificate')); ?>
					</div>							
					<div class="form-group">
						<label>University <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('university')); ?>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="form-group">
						<label>Year <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('year')); ?>
					</div>
					<div class="form-group">
						<label>Percentage <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('percentage')); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			Work Experience Section
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">						
					<div class="form-group">
						<label>Previous Employer <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('previous_employer')); ?>
					</div>							
					<div class="form-group">
						<label>Designation <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('designation')); ?>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="form-group">
						<label>From <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('employee_from')); ?>
					</div>
					<div class="form-group">
						<label>To <span class="mandatory">*</span></label>
						<?php //echo $this->formElement($form->get('employee_to')); ?>
					</div>
				</div>				
			</div>
		</div>
	</div>
	-->
</div>
<!-- /.row -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		<?php if($this->employeeid): ?>
			$('#login-section').hide();
		<?php endif; ?>
		$('#country_id').change(function() {
			countryId = $(this).val();
			getStates(countryId,'');
		});
		countryId = $('#country_id').val();
		if(countryId) {
			getStates(countryId,"<?php echo $this->state_id; ?>");
		}
		
		$('#per_country_id').change(function() {
			perCountryId = $(this).val();
			getPerStates(perCountryId,'');
		});
		perCountryId = $('#per_country_id').val();
		if(perCountryId) {
			getPerStates(perCountryId,"<?php echo $this->per_state_id; ?>");
		}
		
		$('#company_id').change(function() {
			companyId = $(this).val();
			getBranchesByCompany(companyId,'');
		});
		companyId = $('#company_id').val();
		if(companyId) {
			getBranchesByCompany(companyId,"<?php echo $this->branch_id; ?>");
		}
	});	
	
	function getBranchesByCompany(companyId,branchId) {
		$.ajax({
			type:'POST',
			data:{ "companyid":companyId,"branchid":branchId },
			url: BASEPATH + "/branch",
			success:function(reponse) {
				$('#branch_id').html(reponse);
			},
			error:function(error) {
				alert(error);
			}
		});
	}

</script>

<!--
<div class="col-lg-12">
					<div class="form-group">
						<label class="col-lg-3">User Id <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('user_id')); ?></div>
					</div>
					<div class="clear"></div></br>
					<div class="form-group">
						<label class="col-lg-3">Password <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('password')); ?></div>
					</div>
					<div class="clear"></div></br>
					<div class="form-group">
						<label class="col-lg-3">Confirm Password <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('cpassword')); ?></div>
					</div>
				</div>
--->