<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Employee List
            <span class="job-btn pull-right">
                <a href="<?php echo $this->url('new-employee') ?>" class="btn btn-primary">New Employee</a>
            </span>
        </h1>
    </div>	
</div>
<!-- /.row -->

<div class="row">
    <?php echo $this->render('partials/flash-messages') ?>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-table fa-fw"></i> Employee Table</div>
            <div class="panel-body table-responsive">
                <table id="employee-table" class="table table-striped" style="word-wrap:break-word; table-layout:fixed;width:100%;">
                    <thead style="background: none repeat scroll 0 0 #313131;color: #fff;">
                        <tr>
                            <td style="width: 6%;"><strong>#</strong></td>
                            <td style="width: 16%;"><strong>Emp Code</strong></td>
                            <td style="width: 20%;"><strong>Name</strong></td>
                            <td style="width: 22%;"><strong>Email ID</strong></td>
                            <td style="width: 10%;"><strong>User ID</strong></td>							
                            <td style="width: 15%;"><strong>Mobile Number</strong></td>
                            <td style="width: 10%;"><strong>Gender</strong></td>
                            <td style="width: 10%;"><strong>Action</strong></td>
                        </tr>
                    </thead>
                    <tbody style="border-bottom: 3px solid #313131;">
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                        <tr style="background: #fff;border: none;">
                            <td colspan="10" style="width: 100%;" class="text-center">&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#employee-table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": '<?php echo $this->url('employee-list') ?>',
            "bSort": false
        });
    });
</script>