<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">New Employee</h3>
    </div>
</div>
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            Register New Employee
        </div>
        <div class="panel-body">
            <div class="row">
                <?php
                $form = $this->employeeForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                /*foreach ($form as $element) {
                    echo $this->formElement($element);
                    echo $this->formElementErrors($element);
                }*/
                ?>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Member Code</label>
                        <?php echo $this->formElement($form->get('member_id')); ?>
                        <?php if ($this->formElementErrors($form->get('member_id'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('member_id'))) ?></div>
                        <?php endif; ?>	
                    </div>
                    <div class="form-group">
                        <label>Branch <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('company_id')); ?>
                        <?php echo $this->formElement($form->get('branch_id')); ?>
                        <?php if ($this->formElementErrors($form->get('branch_id'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('branch_id'))) ?></div>
                        <?php endif; ?>						
                    </div>
                    <div class="form-group">
                        <label>First Name <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('firstname')); ?>
                        <?php if ($this->formElementErrors($form->get('firstname'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('firstname'))) ?></div>
                        <?php endif; ?>						
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        <?php echo $this->formElement($form->get('lastname')); ?>						
                    </div>
                    <div class="form-group">
                        <label>S/o, D/o, W/o<span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('gardian_name')); ?>
                        <?php if ($this->formElementErrors($form->get('gardian_name'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('gardian_name'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <!--<div class="form-group">
                        <label>Guardian Relation<span class="mandatory">*</span></label>
                    <?php //echo $this->formElement($form->get('gardian_relation')); ?>
                    <?php //if ($this->formElementErrors($form->get('gardian_relation'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php //echo strip_tags($this->formElementErrors($form->get('gardian_relation')))  ?></div>
                    <?php //endif; ?>
                    </div>-->
                    <div class="form-group">
                        <label>Email ID</label>
                        <?php echo $this->formElement($form->get('emailid')); ?>
                        <?php if ($this->formElementErrors($form->get('emailid'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('emailid'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group date">
                        <label>Date Of Birth <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('dob')); ?>
                        <?php if ($this->formElementErrors($form->get('dob'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('dob'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Gender <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('gender')); ?>
                        <?php if ($this->formElementErrors($form->get('gender'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('gender'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Mobile Number <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('mobile_number')); ?>
                        <?php if ($this->formElementErrors($form->get('mobile_number'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('mobile_number'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Country <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('country_id')); ?>
                        <?php if ($this->formElementErrors($form->get('country_id'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('country_id'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>State <span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('state_id')); ?>
                        <?php if ($this->formElementErrors($form->get('state_id'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('state_id'))) ?></div>
                        <?php endif; ?>
                    </div>
                </div>
                <!-- /.col-lg-6 (nested) -->
                <div class="col-lg-6">   
                    <div class="form-group">
                        <label>City</label>
                        <?php echo $this->formElement($form->get('city_id')); ?>
                    </div>  
                    <div class="form-group">
                        <label>Address</label>
                        <?php echo $this->formElement($form->get('address')); ?>
                    </div>
                    <div class="form-group">
                        <label>Nominee Name<span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('nominee_name')); ?>
                        <?php if ($this->formElementErrors($form->get('nominee_name'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_name'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Nominee Relation<span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('nominee_relation')); ?>
                        <?php if ($this->formElementErrors($form->get('nominee_relation'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('nominee_relation'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Nominee Address</label>
                        <?php echo $this->formElement($form->get('nominee_address')); ?>
                    </div>
                    <div class="form-group">
                        <label>Pan Number</label>
                        <?php echo $this->formElement($form->get('pan_number')); ?>
                        <?php if ($this->formElementErrors($form->get('pan_number'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('pan_number'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Employee Code</label>
                        <?php echo $this->formElement($form->get('employee_code')); ?>
                        <?php if ($this->formElementErrors($form->get('employee_code'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('employee_code'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Rank<span class="mandatory">*</span></label>
                        <?php echo $this->formElement($form->get('role_id')); ?>
                        <?php if ($this->formElementErrors($form->get('role_id'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('role_id'))) ?></div>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>Introducer Code</label>
                        <?php echo $this->formElement($form->get('introducer_code')); ?>
                        <?php if ($this->formElementErrors($form->get('introducer_code'))) : ?>
                            <div class="error" style="margin: 3px 0;padding: 4px;color:red;"><?php echo strip_tags($this->formElementErrors($form->get('introducer_code'))) ?></div>
                        <?php endif; ?>
                        <?php echo $this->formElement($form->get('userid')); ?>
                        <?php echo $this->formElement($form->get('password')); ?>

                    </div>
                </div>
                <!-- /.col-lg-6 (nested) -->
                <div class="clear"></div>
                <div class="col-lg-12">
                    <div class="pull-right">
                        <a href="<?php echo $this->url("employees") ?>" class="btn btn-default">Cancel</a>&nbsp;&nbsp;&nbsp;
                        <?php echo $this->formElement($form->get('save')); ?>								
                    </div>							
                </div>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#state_id').change(function () {
            stateId = $(this).val();
            getCities(stateId, '');
        });
        
        $('#member_id').keyup(function () {
            member = $(this).val();
            memberDetsils(member);
        });
        setTimeout(function () {
            getCities($('#state_id').val(), $('#city_id').val());
        }, 200);
        $("#dob").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd',
            maxDate: new Date(),
            yearRange: "-80:+0"

        });


    });
    
    function memberDetsils(member) {
        if (member) {
            $.ajax({
                url: '<?php echo $this->basePath('apis/member') ?>',
                type: 'post',
                data: {code: member},
                success: function (returns) {
                    if (returns.status) {
                        $('#firstname').val(returns.response.data.firstname);
                        $('#lastname').val(returns.response.data.lastname);
                        $('#gardian_name').val(returns.response.data.gardian_name);
                        $('#emailid').val(returns.response.data.emailid);
                        $('#gender').val(returns.response.data.gender);
                        $('#dob').val(returns.response.data.dob);
                        $('#address').val(returns.response.data.address);
                        $('#mobile_number').val(returns.response.data.mobile_number);
                        $('#nominee_name').val(returns.response.data.nominee_name);
                        $('#nominee_relation').val(returns.response.data.nominee_relation);
                        $('#nominee_address').val(returns.response.data.nominee_address);
                        $('#branch_id').val(returns.response.data.branch_id);
                        $('#company_id').val(returns.response.data.company_i);
                        $('#country_id').val(returns.response.data.country_id);
                        $('#state_id').val(returns.response.data.state_id);
                        $('#city_id').val(returns.response.data.city_id);
                    } else {
                        $('#firstname').val('');
                        $('#lastname').val('');
                        $('#gardian_name').val('');
                        $('#emailid').val('');
                        $('#gender').val('');
                        $('#dob').val('');
                        $('#address').val('');
                        $('#mobile_number').val('');
                        $('#nominee_name').val('');
                        $('#nominee_relation').val('');
                        $('#nominee_address').val('');
                        $('#branch_id').val('');
                        $('#company_id').val('');
                        $('#country_id').val('');
                        $('#state_id').val('');
                        $('#city_id').val('');
                    }
                }
            });
        } else {
            $('#firstname').val('');
            $('#lastname').val('');
            $('#gardian_name').val('');
            $('#emailid').val('');
            $('#gender').val('');
            $('#dob').val('');
            $('#address').val('');
            $('#mobile_number').val('');
            $('#nominee_name').val('');
            $('#nominee_relation').val('');
            $('#nominee_address').val('');
            $('#branch_id').val('');
            $('#company_id').val('');
            $('#country_id').val('');
            $('#state_id').val('');
            $('#city_id').val('');
        }
    }
    function getCities(stateid, cityid) {
        $.ajax({
            type: "POST",
            async: false,
            url: '<?php echo $this->basepath(); ?>/city',
            data: {'stateid': stateid, 'cityid': cityid},
            success: function (result) {
                var html = '<option value="">-Choose City-</option>';
                if (result.status) {
                    for (x in result.response.data) {
                        if (result.response.data[x].selected) {
                            html += '<option selected value="' + result.response.data[x].id + '">' + result.response.data[x].name + '</option>';
                        } else {
                            html += '<option value="' + result.response.data[x].id + '">' + result.response.data[x].name + '</option>';
                        }
                    }
                }
                $('#city_id').html(html);
            }
        });
    }
</script>