<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">New Role
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('roles')?>" class="btn btn-primary">Employee Role</a>
			</span>
		</h1>
		<?php 
			if(!empty($this->flashMessages[0])) {
				foreach($this->flashMessages[0] as $class => $message) {
					echo '<div class="'.$class.'">'.$message.'</div>';	
				}
			}
			if ($this->error) {
				echo '<div class="error">'.$this->error.'</div>';	
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<form method="post" class="role">
		<div class="col-lg-12">			
			<div class="panel panel-default">
				<div class="panel-heading">New Role Section</div>
				<div class="panel-body">
					<div class="col-lg-12">
						<div class="form-group">
							<label class="col-lg-2">Role Name <span class="mandatory">*</span></label>
							<div class="col-lg-6"><input type="text" class="form-control" ></div>
						</div>
						<div class="clear"></div><br/>
						<div class="form-group">
							<label class="col-lg-2">Role Description</label>
							<div class="col-lg-6"><textarea cols="50" rows="3" class="form-control"></textarea></div>
						</div>
						<div class="clear"></div><br/>
						<div class="form-group">
							<label class="col-lg-2">Status</label>
							<div class="col-lg-6">
								<select  class="form-control">
									<option value="1">Yes</option>
									<option value="0">NO</option>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">Role Permission Section</div>
				<div class="panel-body">
					<div class="permission">
						<div class="col-lg-12">
							<?php foreach($this->menus as $menu): ?>
							<?php if(!empty($menu['subMenuList'])): ?>
								<div class="module">
									<label><input type="checkbox" name="menu[<?php echo $menu['id'] ?>][]">&nbsp;<?php echo $menu['name']; ?></label>
									<?php foreach($menu['subMenuList'] as $submenu): ?>
										<div class="menu-permission">
											<span class="menu"><label><input type="checkbox" name="menu[<?php echo $submenu['id'] ?>][]">&nbsp;<?php echo $submenu['name'] ?>:</label></span>
											<?php if(!empty($submenu['subMenuList'])): ?>
												<?php foreach($submenu['subMenuList'] as $smenu): ?>
												<div class="menu-permission">
													<span class="menu"><label><input type="checkbox">&nbsp;<?php echo $smenu['name'] ?>:</label></span>
													<span><input type="checkbox" name="insert[<?php echo $smenu['id'] ?>][]">&nbsp;Insert</span>
													<span><input type="checkbox" name="update[<?php echo $smenu['id'] ?>][]">&nbsp;Update</span>
													<span><input type="checkbox" name="delete[<?php echo $smenu['id'] ?>][]">&nbsp;Delete</span>
													<span><input type="checkbox" name="view[<?php echo $smenu['id'] ?>][]">&nbsp;View</span>
												</div>								
												<?php endforeach; ?>	
											<?php else: ?>
											<span><input type="checkbox" name="insert[<?php echo $submenu['id'] ?>][]">&nbsp;Insert</span>
											<span><input type="checkbox" name="update[<?php echo $submenu['id'] ?>][]">&nbsp;Update</span>
											<span><input type="checkbox" name="delete[<?php echo $submenu['id'] ?>][]">&nbsp;Delete</span>
											<span><input type="checkbox" name="view[<?php echo $submenu['id'] ?>][]">&nbsp;View</span>
											<?php endif; ?>
										</div>
									<?php endforeach; ?>
								</div>
							<?php endif; ?>
							<?php endforeach; ?>
						</div>
					</div>
					<input type="submit" class="btn btn-primary" name="save-role" value="Save Role">	
				</div>
			</div>
		</div>
	</form>
</div>
<!--
<div class="panel-body">
	<div class="col-lg-12">					
		<div class="permission">
			<div class="module">
				<label><input type="checkbox">&nbsp;Manage Member</label>
				<div class="menu-permission">
					<span class="menu"><label><input type="checkbox">&nbsp;Members:</label></span>
					<span><input type="checkbox">&nbsp;Insert</span>
					<span><input type="checkbox">&nbsp;Update</span>
					<span><input type="checkbox">&nbsp;Delete</span>
					<span><input type="checkbox">&nbsp;View</span>
				</div>
			</div>
			<div class="module">
				<label><input type="checkbox">&nbsp;Manage Investment</label>
				<div class="menu-permission">
					<span class="menu"><label><input type="checkbox">&nbsp;Investors:</label></span>
					<div class="menu-permission">
						<span class="menu"><label><input type="checkbox">&nbsp;Investment1:</label></span>
						<span><input type="checkbox">&nbsp;Insert</span>
						<span><input type="checkbox">&nbsp;Update</span>
						<span><input type="checkbox">&nbsp;Delete</span>
						<span><input type="checkbox">&nbsp;View</span>
					</div>								
				</div>
				<div class="menu-permission">
					<span class="menu"><label><input type="checkbox">&nbsp;New Installment:</label></span>
					<span><input type="checkbox">&nbsp;Insert</span>
					<span><input type="checkbox">&nbsp;Update</span>
					<span><input type="checkbox">&nbsp;Delete</span>
					<span><input type="checkbox">&nbsp;View</span>
				</div>
			</div>
		</div>
	</div>
</div>
-->