<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">New Company</h1>
		<a href="<?php echo $this->url('company-list')?>"><button class="btn btn-success pull-right" style="margin-top: -63px;">Company List</button></a>
		<?php 
			if(!empty($this->errors)) {
				echo '<div class="alert alert-danger">';
				foreach($this->errors as $class => $msgArr) {
					foreach($msgArr as $message) {
						echo $message.'<br>';
					}
				}
				echo '</div>';
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">			
		<div class="panel panel-default">
			<div class="panel-heading">New Company Section</div>
			<div class="panel-body">
				<?php
					$form = $this->companyForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-12">
					<div class="form-group">
						<label class="col-lg-2">Company Name <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('name')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Phone Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('phone_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Mobile Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('mobile_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Country <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('country_id')); ?></div>
					</div>
					<div class="clear"></div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">State <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('state_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">City <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('city')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Address <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('address')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Pincode <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('pincode')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Logo <span class="mandatory">*</span></label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('logo')); ?>
							<?php if($this->logo): ?>
							<div class="clear"></div>
							<img class="company-logo" src="<?php echo $this->basePath(); ?>/uploads/company/<?php echo $this->logo; ?>" >
							<?php endif; ?>
						</div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Status <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('status')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">&nbsp;</label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('save-company')); ?>
							<?php echo $this->formElement($form->get('reset')); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	
<!-- /.row -->
<script type="text/javascript">
	
    function getStatess() {
		$.ajax({
			type: "POST",
			url: '<?php echo $this->basePath(); ?>/states',
			data: {countryid:$('#country_id').val(), 'stateid':"<?php echo $this->stateid; ?>"},
			success: function(result) {
				var html = '<option value="">-Choose State-</option>';
				if(result.status) {					
					for(x in result.response.data) {
						if(result.response.data[x].selected) {
							html += '<option selected value="'+result.response.data[x].id+'">'+result.response.data[x].name+'</option>';
						} else {
							html += '<option value="'+result.response.data[x].id+'">'+result.response.data[x].name+'</option>';
						}
					}
				}
				$('#state_id').html(html);
			}
		});
	}    

</script>