<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Company</h3>
		<a href="<?php echo $this->url('company-list')?>"><button class="btn btn-success pull-right" style="margin-top: -63px;">Company List</button></a>
		<?php 
			if(!empty($this->errors)) {
				foreach($this->errors as $class => $msgArr) {
					foreach($msgArr as $message) {
						echo '<div class="error">'.$message.'</div>';
					}
				}
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">			
		<div class="panel panel-default">
			<div class="panel-heading">New Company Section</div>
			<div class="panel-body">
				<?php
					$form = $this->companyForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-12">
					<div class="form-group">
						<label class="col-lg-2">Company Name <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('company_name')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Phone Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('phone_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Mobile Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('mobile_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Country <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('country_id')); ?></div>
					</div>
					<div class="clear"></div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">State <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('state_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">City <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('city')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Address <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('address')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Pincode <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('pincode')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Status <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('status')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">&nbsp;</label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('save-company')); ?>
							<?php echo $this->formElement($form->get('reset')); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	