<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Companies List
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('new-company')?>" class="btn btn-primary">New Company</a>
			</span>
		</h1>
		<?php echo $this->render('partials/flash-messages')?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"><i class="fa fa-table fa-fw"></i> Company Table</div>
			<!-- /.panel-heading -->
			<div class="panel-body table-responsive">
				<?php if(count($this->companies) > 0): ?>
					<table class="table table-striped table-bordered table-hover" id="company-list">
					<thead>
						<tr>
							<th>#</th>
							<th>Company Name</th>
							<th>Phone Number</th>
							<th>City</th>
							<th>Status</th>
							<th>Ation</th>
						</tr>
					</thead>
					<tbody>
					<?php $count=1; foreach($this->companies as $comoany): ?>
						<tr>
							<td><?php echo $count; ?></td>
							<td><?php echo $comoany->name; ?></td>
							<td><?php echo $comoany->phone_no; ?></td>
							<td><?php echo $comoany->city; ?></td>
							<td><?php echo ($comoany->status==1)?'Active':'Inactive'; ?></td>
							<td>
								<a title="View" href="<?php echo $this->basePath(); ?>/new-company/<?php echo $comoany->id; ?>"><i class="fa fa-search "></i></a>&nbsp;| 
								<a title="Edit" href="<?php echo $this->basePath(); ?>/new-company/<?php echo $comoany->id; ?>"><i class="fa fa-pencil"></i></a>&nbsp;| 
								<a title="Delete" href="javascript:void(0);" onclick="deleteComoany('<?php echo $comoany->id; ?>')"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					<?php $count++; endforeach; ?>
					</tbody>
					</table>
				<?php else: ?>
				<?php endif; ?>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->			
	</div>
	<!-- /.col-lg-12 -->		
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
	$('#company-list').DataTable({
		responsive: true
	});	
});
function deleteComoany(companyId) {
	if(confirm('Are you sure for delete this company?')) {
		window.location.href = '<?php echo $this->basePath(); ?>/delete-company/'+companyId;
	}
}
</script>