<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">New Branch
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('branch-list')?>" class="btn btn-primary">Branch List</a>
			</span>
		</h3>
		<?php 
			if(!empty($this->flashMessages[0])) {
				foreach($this->flashMessages[0] as $class => $message) {
					echo '<div class="'.$class.'">'.$message.'</div>';	
				}
			}
			if ($this->error) {
				echo '<div class="error">'.$this->error.'</div>';	
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">			
		<div class="panel panel-default">
			<div class="panel-heading">New Branch Section</div>
			<div class="panel-body">
				<?php
					$form = $this->branchForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-6">
					<div class="form-group">
						<label class="col-lg-3">Branch Name <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('branch_name')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Parent Branch</label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('parent_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Company</label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('company_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Phone Number <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('phone_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Mobile Number <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('mobile_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Country <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('country_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					</div>
					<div class="col-lg-6">
					<div class="form-group">
						<label class="col-lg-3">State <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('state_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">City <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('city')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Address <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('address')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Pincode <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('pincode')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-3">Status <span class="mandatory">*</span></label>
						<div class="col-lg-9"><?php echo $this->formElement($form->get('status')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-10">&nbsp;</label>
						<div class="col-lg-2">
							<?php echo $this->formElement($form->get('save-branch')); ?>
							<?php //echo $this->formElement($form->get('reset')); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>