<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">New Branch
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('branch-list')?>" class="btn btn-primary">Branch List</a>
			</span>
		</h1>
		<?php 
			if(!empty($this->errors)) {
				echo '<div class="alert alert-danger">';
				foreach($this->errors as $class => $msgArr) {
					foreach($msgArr as $message) {
						echo $message.'<br>';
					}
				}
				echo '</div>';
			}
		?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">			
		<div class="panel panel-default">
			<div class="panel-heading">New Branch Section</div>
			<div class="panel-body">
				<?php
					$form = $this->branchForm;
					$form->prepare();
					echo $this->form()->openTag($form);
				?>
				<div class="col-lg-12">
					<div class="form-group">
						<label class="col-lg-2">Company <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('company_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Parent Branch</label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('parent_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Branch Name <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('name')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Branch Code </label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('code')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Phone Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('phone_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Mobile Number <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('mobile_no')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Country <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('country_id')); ?></div>
					</div>
					<div class="clear"></div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">State <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('state_id')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">City <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('city')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Address <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('address')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Pincode <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('pincode')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">Status <span class="mandatory">*</span></label>
						<div class="col-lg-6"><?php echo $this->formElement($form->get('status')); ?></div>
					</div>
					<div class="clear"></div><br/>
					<div class="form-group">
						<label class="col-lg-2">&nbsp;</label>
						<div class="col-lg-6">
							<?php echo $this->formElement($form->get('save-branch')); ?>
							<?php echo $this->formElement($form->get('reset')); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	
<!-- /.row -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('#country_id').change(function() {
			countryId = $(this).val();
			getStates(countryId,'');
		});
		countryId = $('#country_id').val();
		if(countryId) {
			getStates(countryId,"<?php echo $this->stateid; ?>");
		}
		
		$('#company_id').change(function() {
			companyId = $(this).val();
			getBranches(companyId,'');
		});
		companyId = $('#company_id').val();
		if(companyId) {
			getBranches(companyId,"<?php echo $this->branchid; ?>");
		}
	});	
</script>