<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Braches List
			<span class="job-btn pull-right">
				<a href="<?php echo $this->url('new-branch')?>" class="btn btn-primary">New Branch</a>
			</span>
		</h1>
		<?php echo $this->render('partials/flash-messages')?>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading"><i class="fa fa-table fa-fw"></i> Branch Table</div>
			<!-- /.panel-heading -->
			<div class="panel-body table-responsive">
				<?php if(count($this->branches) > 0): ?>
					<table class="table table-striped table-bordered table-hover" id="branch-list">
					<thead>
						<tr>
							<th>#</th>
							<th>Branch Name</th>
							<th>Branch Code</th>
							<th>Company Name</th>
							<th>Phone Number</th>
							<th>City</th>
							<th>Status</th>
							<th>Ation</th>
						</tr>
					</thead>
					<tbody>
					<?php $count=1; foreach($this->branches as $branch): ?>
						<tr>
							<td><?php echo $count; ?></td>
							<td><?php echo $branch->name; ?></td>
							<td><?php echo $branch->code; ?></td>
							<td><?php echo $branch->companyname; ?></td>
							<td><?php echo $branch->phone_no; ?></td>
							<td><?php echo $branch->city; ?></td>
							<td><?php echo ($branch->status==1)?'Enable':'Desable'; ?></td>
							<td>
								<a title="View" href="<?php echo $this->basePath(); ?>/new-branch/<?php echo $branch->id; ?>"><i class="fa fa-search "></i></a>&nbsp;| 
								<a title="Edit" href="<?php echo $this->basePath(); ?>/new-branch/<?php echo $branch->id; ?>"><i class="fa fa-pencil"></i></a>&nbsp;| 
								<a title="Delete" href="javascript:void(0);" onclick="deleteBranch('<?php echo $branch->id; ?>')"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					<?php $count++; endforeach; ?>
					</tbody>
					</table>
				<?php else: ?>
                                    <div class="text-center">No branches found<div>
				<?php endif; ?>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->			
	</div>
	<!-- /.col-lg-12 -->		
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
	$('#branch-list').DataTable({
		responsive: true
	});	
});
function deleteBranch(branchId) {
	if(confirm('Are you sure for delete this branch?')) {
		window.location.href = '<?php echo $this->basePath(); ?>/delete-branch/'+branchId;
	}
}
</script>